apiVersion: v1
kind: Namespace
metadata:
  name: labo03
  labels:
    name: labo03
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: labo03
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: richardvanraeshowest/hello-world-nginx:v2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  generateName: mypod-
  namespace: labo03 # Enter your namespace here
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: richardvanraeshowest/hello-world-nginx:v2
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: labo03
spec:
  selector:
    app: nginx
  ports:
  - nodePort: 31234
    port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer